apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dguhox89v-nodejs
  janus-idp.io/tekton: dguhox89v-nodejs
  backstage.io/kubernetes-id: dguhox89v-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dguhox89v-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
